server:
  port: 8085

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/boardCRUD
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # show, format sql은 콘솔창에서 sql들을 보기좋게 해준다.
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    board.crud: DEBUG