server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/boardCRUD
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create # ?????? ???? ??
    properties:
      hibernate:
        show_sql: true # ?? ??
        format_sql: true # ??? ?? ????.
    #database-platform: org.hibernate.dialect.MySQL5Dialect